feat: unit place selector uses schoolsAndKindergartens query
City-of-Helsinki/palvelutarjotin-admin pull request #236
Opened 2021-11-11 11:16 UTC by nikomakela

API returns all the units (1000+ pcs) all at once from schoolsAndKindergartens graphql query. The Enrolment form autosuggest field for unit selection should be able to filter the list of units with an input value.

PT-1298 PT-1313.

Same ticket in palvelutarjotin-ui: https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/173

2021-11-11 11:24 UTC, nikomakela commented
- [ ] Tests are still missing

2021-11-11 11:45 UTC, Sartonon requested changes
Looks good but some code should be moved out of PlaceText component :)

2021-11-11 11:45 UTC, Sartonon commented on src/domain/place/placeText/PlaceText.tsx
> +      : '';
Same as in kultus-ui PR. I think this doesn't belong in this component

2021-11-16 14:02 UTC, Sartonon approved these changes
Looks good :)

2021-11-18 11:57 UTC, merged