feat: implement new occurrence form with HDS inputs
City-of-Helsinki/palvelutarjotin-admin pull request #250
Opened 2022-01-05 17:13 UTC by Sartonon

## Description :sparkles:

## Issues :bug:
### Closes :no_good_woman:
**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):** 

### Related :handshake:

## Testing :alembic:
### Automated tests :gear:️

### Manual testing :construction_worker_man:

## Screenshots :camera_flash:

## Additional notes :spiral_notepad:

2022-01-17 13:56 UTC, Jokinen approved these changes
Looks good to me.

Very minor comments on the UI:
<img width="1303" alt="Screenshot 2022-01-17 at 15 53 42" src="https://user-images.githubusercontent.com/9090689/149781330-e0dddc14-ba71-4177-8969-d726a149b16c.png">

Language select can't fit value on an average laptop screen.

Quite extensive changes when it comes to the code, but couldn't spot anything I wanted to point out.

2022-01-17 13:56 UTC, Jokinen commented on src/domain/occurrence/occurrencesFormPart/OccurrencesFormPart.tsx
> +  // TODO: what to do is this is called when going to publish page and confirmation modal is opened?
Is this a TODO you intended to resolve in this PR?

2022-01-18 06:44 UTC, Sartonon commented on src/domain/occurrence/occurrencesFormPart/utils.ts
> +export const getOccurrencerWithSameDateAlreadyExists = (
typo (note for myself)

2022-01-19 07:37 UTC, nikomakela commented on src/domain/occurrence/occurrencesFormPart/utils.ts
> +export const getOccurrencerWithSameDateAlreadyExists = (
- [ ] fix a typo ;)

2022-01-19 07:40 UTC, nikomakela requested changes
Needs some Swedish translations before can be merged

2022-01-19 07:40 UTC, nikomakela commented on src/domain/app/i18n/sv.json
> +    "labelEndDate": "SV: End date",
Needs a translation

2022-01-19 07:40 UTC, nikomakela commented on src/domain/app/i18n/sv.json
> +    }
Translations needed

2022-01-19 07:40 UTC, nikomakela commented on src/domain/app/i18n/sv.json
> +        "invalid": "SV: Use form D.M.YYYY",
translations needed

2022-01-19 07:40 UTC, nikomakela commented on src/domain/app/i18n/sv.json
> +        "invalid": "SV: Time is invalid",
translations needed

2022-01-19 07:48 UTC, nikomakela commented
I had some serious issues with the datepicker input when I tested it. I could not set a date there - at all. 
![image](https://user-images.githubusercontent.com/389204/150086726-6cd7e3de-94dd-4d23-b736-aae6848a2dab.png)
Browser is the Chrome, but it's in English - could it make the difference?

2022-01-24 13:56 UTC, merged